### ISSUE TITLE
Cancelling jobs leads to crashes

### ISSUE THREAD

**Issue by skurfuerst** [Flowpack/prunner#8] opened 2021-08-03 07:04 UTC
```
  INFO[0655] Canceling job             component=api jobID=1bb89e0a-3823-4027-bf06-22c531d626b8
  INFO[0655] "POST http://localhost:9009/job/cancel?id=1bb89e0a-3823-4027-bf06-22c531d626b8 HTTP/1.1" from 127.0.0.1:52674 - 200 5B in 75.9891ms component=api
  INFO[0655] Job scheduled             component=api jobID=886f8e14-a651-492f-9069-ba291a9bc808 pipeline=do_content_release user=admin
  INFO[0655] "POST http://localhost:9009/pipelines/schedule HTTP/1.1" from 127.0.0.1:52678 - 202 49B in 1.6136ms component=api
panic: close of closed channel

goroutine 121 [running]:
networkteam.com/lab/prunner/taskctl.(*TaskRunner).Run.func1(0xc00007a000)
	/Users/sebastian/src/flowpack/prunner/taskctl/runner.go:110 +0x77
networkteam.com/lab/prunner/taskctl.(*TaskRunner).Run(0xc00007a000, 0xc00019a9c0, 0xaee860, 0xc00009e1d0)
	/Users/sebastian/src/flowpack/prunner/taskctl/runner.go:207 +0x660
networkteam.com/lab/prunner/taskctl.(*Scheduler).runStage(0xc000249860, 0xc000079290, 0xe0b7e0, 0x406365)
	/Users/sebastian/src/flowpack/prunner/taskctl/scheduler.go:163 +0xb3
networkteam.com/lab/prunner/taskctl.(*Scheduler).Schedule.func1(0xc0005e4000, 0xc000249860, 0xc0005e4010, 0xc000240000, 0xc000079290)
	/Users/sebastian/src/flowpack/prunner/taskctl/scheduler.go:93 +0xb0
created by networkteam.com/lab/prunner/taskctl.(*Scheduler).Schedule
	/Users/sebastian/src/flowpack/prunner/taskctl/scheduler.go:85 +0x15d
```

**Comment by skurfuerst** [comment] 2021-08-03 08:23
I have a workaround for this

**Comment by hlubek** [comment] 2021-08-23 13:21
I think this is caused by multiple parallel `Run(t *task.Task)` invocations closing the same channel `doneCh` in a shared runner. I'm not sure if the workaround is fully okay: it uses a read lock (could lead to data races) and subsequent calls to `Cancel` would no be allowed after `r.cacneling = false`.

What we want to achieve here is basically a fan-out and wait until all `Run` calls have finished after canceling the context. I'd suggest to use a `sync.WaitGroup` for this case, since it is robust for funneling results from multiple goroutines.

**Comment by skurfuerst** [comment] 2021-08-30 11:49
@hlubek confirmed, you are totally right :) I just had the original issue with the closed channel again... will apply your patch and retry.

**Comment by skurfuerst** [comment] 2021-12-29 09:17
@hlubek at least it did never appear for us in production :)

**Closed** 2021-12-29 09:17 UTC
